[build]
  base = "frontend"
  command = "npm --prefix ../netlify/functions ci || npm --prefix ../netlify/functions install && npm ci && npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  # Optional (not strictly required for `openai`, but safe to include)
  external_node_modules = ["openai"]
  # Paths here are relative to the base ("frontend"), so drop the "frontend/" prefix:
  included_files = ["src/data/resume.json"]
