[build]
  base = "frontend"
  command = "npm --prefix ../netlify/functions install && npm install && npm run build"
  publish = "dist"

[functions]
  directory = "../netlify/functions"   # 👈 important when base="frontend"
  node_bundler = "esbuild"
  external_node_modules = ["openai"]   # safe for SDK v4
  included_files = ["src/data/resume.json"]
