[build]
  base = "frontend"
  command = "npm install && npm run build"   # run in /frontend (no --prefix)
  publish = "dist"
  functions = "../netlify/functions"         # functions live one level up (repo root)

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler  = "esbuild"
  included_files = ["frontend/src/data/resume.json"]
