[build]
  # Install root deps (for Functions), then frontend deps, then build the app.
  command   = "npm install && npm install --prefix frontend && npm run build --prefix frontend"
  publish   = "frontend/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler           = "esbuild"
  external_node_modules  = ["openai"]
  included_files         = ["frontend/src/data/resume.json"]
