[build]
  base = "frontend"
  command = "npm --prefix ../netlify/functions install && npm install && npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["openai"]
  included_files = ["src/data/resume.json"]
