[build]
  base = "frontend"
  command = "npm --prefix ../netlify/functions install && npm install && npm run build"
  publish = "dist"

[functions]
  # 👇 tell Netlify where your functions really are (relative to base)
  directory = "../netlify/functions"
  node_bundler = "esbuild"
  included_files = ["src/data/resume.json"]
