[build]
  # Build the frontend without using "base" so paths are unambiguous
  command  = "npm install --prefix frontend && npm run build --prefix frontend"
  publish  = "frontend/dist"
  functions = "netlify/functions"   # functions folder at repo root

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler = "esbuild"
