[build]
  # Install root deps (for functions, e.g., "openai"), then frontend deps, then build
  command   = "npm install && npm install --prefix frontend && npm run build --prefix frontend"
  publish   = "frontend/dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to   = "/.netlify/functions/:splat"
  status = 200

[functions]
  node_bundler  = "esbuild"
  # Ensure resume.json is copied into the function bundle at deploy time
  included_files = ["frontend/src/data/resume.json"]
